---
title: "Economic Data"
author: "Grant Morrison"
date: "7/1/2021"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}
library(ggplot2)
library(tidyverse)
```


## Real Consumption



```{r}
consumption <- read.csv("consumption_data.csv")
```




```{r}
d1 <- 2007.5
d2 <- 2009.5
```



```{r,fig.width=11, fig.height=7}
ggplot(data = consumption,aes(x=year, y = rpce)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_bar(fill = "#002776",stat="identity",width = .7) +
  geom_hline(yintercept = 0,lty = 2, col = "black") +
  ylab("Percent Change from Preceding Period") +
  xlab("Year") +
  theme_bw() +
  ggtitle("Real Personal Consumption Expeditures 2005 - 2020")  +
  theme(plot.title = element_text(hjust = 0.5))
```


### Real Personal Consumption: Nondurable Goods


```{r, fig.width=11, fig.height=7}
ggplot(data = consumption,aes(x=year, y = rpcend)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_bar(fill = "4a9d36",stat="identity",width = .7) +
  geom_hline(yintercept = 0,lty = 2, col = "black") +
  ylab("Percent Change from Preceding Period") +
  xlab("Year") +
  theme_bw() +
  ggtitle("Real Personal Consumption Expeditures: Nondurable Goods 2005 - 2020")  +
  theme(plot.title = element_text(hjust = 0.5))

```



### Real Personal Consumption Durable Goods


```{r,fig.width=11, fig.height=7}
ggplot(data = consumption,aes(x=year, y = rpcedg)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_bar(fill = "#4a9d36",stat="identity",width = .7) +
  geom_hline(yintercept = 0,lty = 2, col = "black") +
  ylab("Percent Change from Preceding Period") +
  xlab("Year") +
  theme_bw() +
  ggtitle("Real Personal Consumption Expeditures: Durable Goods 2005 - 2020") +
  theme(plot.title = element_text(hjust = 0.5))
```



### Real Personal Consumption Services

```{r,fig.width=11, fig.height=7}
ggplot(data = consumption,aes(x=year, y = rpces)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_bar(fill = "#d2492a",stat="identity",width = .7) +
  geom_hline(yintercept = 0,lty = 2, col = "black") +
  ylab("Percent Change from Preceding Period") +
  xlab("Year") +
  theme_bw() +
  ggtitle("Real Personal Consumption Expeditures: Services 2005 - 2020") +
  theme(plot.title = element_text(hjust = 0.5))
```





## Real Disposable Personal Income


```{r}
dpi <- read.csv("real_disposable_income.csv")
```



Recession dates for the charts
```{r}
d1 <- as.Date("12/01/07", "%m/%d/%y")
d2 <- as.Date("06/01/09", "%m/%d/%y")
```
```{r}
dpi$DATE <- as.Date(dpi$DATE, "%m/%d/%y")
```




```{r,fig.width=11, fig.height=7}
ggplot(data = dpi, aes(x=DATE,y=DSPIC96)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_line(col="navy") +
  theme_bw() +
  ylab("Billions of Chained 2012 Dollars") +
  xlab("Date(Monthly)") +
  ggtitle("Real Disposable Personal Income")  +
  theme(plot.title = element_text(hjust = 0.5))

```




### Unemployment


```{r}
unemployment <- read.csv("unemployment.csv")
```


```{r}
unemployment$DATE <- as.Date(unemployment$DATE, "%Y-%m-%d")
```

```{r,fig.width=11, fig.height=7}
ggplot(data = unemployment, aes(x=DATE,y=UNRATE)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_line(col="navy") +
  theme_bw() +
  ylab("Unemployment Rate(Percent)") +
  xlab("Date(Monthly)") +
  ggtitle("Unemployment Rate")  +
  theme(plot.title = element_text(hjust = 0.5))
```






### Real GDP



```{r}
real_gdp <- read.csv("real_gdp.csv")
```

```{r}
real_gdp$DATE <- as.Date(real_gdp$DATE, "%Y-%m-%d")
```



```{r,fig.width=11, fig.height=7}
ggplot(data = real_gdp, aes(x=DATE,y=GDPC1)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_line(col="navy") +
  theme_bw() +
  ylab("Billions of Chained 2012 Dollars") +
  xlab("Date(Quarterly)") +
  ggtitle("Real Gross Domestic Product")  +
  theme(plot.title = element_text(hjust = 0.5))
```






### Debt to GDP


```{r}
debt_gdp <- read.csv("debt_to_gdp.csv")
```

```{r}
debt_gdp$DATE <- as.Date(debt_gdp$DATE, "%Y-%m-%d")
```


```{r,fig.width=11, fig.height=7}
ggplot(data = debt_gdp, aes(x=DATE,y=GFDEGDQ188S)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_line(col="navy") +
  theme_bw() +
  ylab("Percent") +
  xlab("Date(Quarterly)") +
  ggtitle("Total Public Debt as a Percent of Gross Domestic Product")  +
  theme(plot.title = element_text(hjust = 0.5))
```

### Personal Savings Rate

```{r}
personal_savings <- read.csv("personal_savings_rate.csv")
```


```{r}
personal_savings$DATE <- as.Date(personal_savings$DATE, "%Y-%m-%d")
```


```{r,fig.width=11, fig.height=7}
ggplot(data = personal_savings, aes(x=DATE,y=PSAVERT)) +
  geom_rect(aes(xmin = d1,xmax=d2,ymin=-Inf,ymax=Inf), alpha = .3, fill ="lightgrey") +
  geom_line(col="navy") +
  theme_bw() +
  ylab("Percent") +
  xlab("Date(Monthly)") +
  ggtitle("Personal Savings Rate as a Percentage of Disposable Income")  +
  theme(plot.title = element_text(hjust = 0.5))
```





